import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "../../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Share Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <h1 className="h1">Welcome to Share Page1</h1>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
