import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/nav-bar";
import Header from "@/components/header";
import SideNav from "@/components/side-nav";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />

        <div className="drawer lg:drawer-open">
          <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />

          <div className="drawer-content">
            <Header />
            {children}
          </div>
          <div className="drawer-side">
            <label
              htmlFor="my-drawer-2"
              aria-label="close sidebar"
              className="drawer-overlay"
            ></label>
            <ul className="menu bg-base-100 text-base-content min-h-full w-80 p-4">
              <ul className="menu bg-base-100 rounded-box w-56">
                <li>
                  <Link className="rounded-full" href="/photos">
                    Photos
                  </Link>
                </li>
                <li>
                  <Link className="rounded-full" href="/albums">
                    Albums
                  </Link>
                </li>
                <li>
                  <Link className="rounded-full" href="/explorer">
                    Explorer
                  </Link>
                  <ul>
                    <li>
                      <Link className="rounded-full" href="/people">
                        People
                      </Link>
                    </li>
                    <li>
                      <Link className="rounded-full" href="/places">
                        Places
                      </Link>
                    </li>
                    <li>
                      <Link className="rounded-full" href="/favorites">
                        Favorites
                      </Link>
                    </li>
                  </ul>
                </li>
                <li>
                  <Link className="rounded-full" href="/trash">
                    Trash
                  </Link>
                </li>
              </ul>
            </ul>
          </div>
        </div>
      </body>
    </html>
  );
}
