import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/nav-bar";
import Header from "@/components/header";
import SideBar from "@/components/side-bar";

import styles from "./page.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Echo Photos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.container}>
          {/* <header className={styles.header}></header> */}
          <div className={styles.container2}>
            {/* <section className={styles.sidebar} /> */}
            <main className={styles.content}>{children}</main>
          </div>
          <NavBar></NavBar>
        </div>
      </body>
    </html>
  );
}
