CREATE DATABASE moments DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;

USE moments;

CREATE TABLE photos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  file_path VARCHAR(255) NOT NULL UNIQUE,
  check_sum CHAR(32) NOT NULL,
  shot_time DATETIME NOT NULL,
  modified_time DATETIME NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE albums (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE album_photos (
  album_id INT NOT NULL,
  photo_id INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (album_id, photo_id),
  FOREIGN KEY (album_id) REFERENCES albums(id) ON DELETE CASCADE,
  FOREIGN KEY (photo_id) REFERENCES photos(id) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE thumbnails (
  id INT AUTO_INCREMENT PRIMARY KEY,
  check_sum CHAR(32) NOT NULL,
  file_path VARCHAR(255) NOT NULL UNIQUE,
  width SMALLINT NOT NULL,
  height SMALLINT NOT NULL,
  format VARCHAR(50) NOT NULL,
  FOREIGN KEY (check_sum) REFERENCES photos(check_sum) ON DELETE CASCADE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE exifs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  check_sum CHAR(32) NOT NULL UNIQUE,
  shot_time DATETIME NOT NULL,
  camera_make VARCHAR(50) DEFAULT NULL,
  camera_model VARCHAR(50) DEFAULT NULL,
  iso SMALLINT DEFAULT NULL,
  gps_latitude FLOAT DEFAULT NULL,
  gps_longitude FLOAT DEFAULT NULL,
  FOREIGN KEY (check_sum) REFERENCES photos(check_sum) ON DELETE CASCADE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;